[32mINFO[0m:     Will watch for changes in these directories: ['/home/martin/Fuentes/mentoria_josu/api']
[32mINFO[0m:     Will watch for changes in these directories: ['/home/martin/Fuentes/mentoria_josu/api']
[32mINFO[0m:     Started server process [[36m49316[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: %d format: a real number is required, not str
Call stack:
  File "/home/martin/Fuentes/mentoria_josu/api/api/server.py", line 18, in <module>
    server.run()
  File "/home/martin/.cache/pypoetry/virtualenvs/api-yfzopysp-py3.11/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/usr/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/martin/.cache/pypoetry/virtualenvs/api-yfzopysp-py3.11/lib/python3.11/site-packages/uvicorn/server.py", line 78, in serve
    await self.startup(sockets=sockets)
  File "/home/martin/.cache/pypoetry/virtualenvs/api-yfzopysp-py3.11/lib/python3.11/site-packages/uvicorn/server.py", line 177, in startup
    self._log_started_message(listeners)
  File "/home/martin/.cache/pypoetry/virtualenvs/api-yfzopysp-py3.11/lib/python3.11/site-packages/uvicorn/server.py", line 218, in _log_started_message
    logger.info(
Message: 'Uvicorn running on %s://%s:%d (Press CTRL+C to quit)'
Arguments: ('http', '127.0.0.1', '8080')
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m49316[0m]
